//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_prop
    {
        public a_prop()
        {
            this.wf_process = new HashSet<wf_process>();
        }
    
        public byte[] v { get; set; }
        public int id { get; set; }
        public Nullable<int> prop_id { get; set; }
        public string code { get; set; }
        public string value { get; set; }
        public Nullable<int> num { get; set; }
        public string name { get; set; }
        public string path { get; set; }
    
        public virtual ICollection<wf_process> wf_process { get; set; }
    }
}
