//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_tableLink
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public Nullable<int> tableFrom_id { get; set; }
        public Nullable<int> rowFrom_id { get; set; }
        public Nullable<int> tableTo_id { get; set; }
        public Nullable<int> rowTo_id { get; set; }
    }
}
