//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_userLayout
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string layout_id { get; set; }
        public string userData { get; set; }
        public string user_name { get; set; }
    }
}
