//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_userField
    {
        public int id { get; set; }
        public Nullable<int> fieldNumber { get; set; }
        public Nullable<int> fieldList_id { get; set; }
        public string caption { get; set; }
        public int table_id { get; set; }
        public Nullable<Sasha.Lims.DataAccess.Entities.Constants.UserFieldDataType> dataType { get; set; }
        public Nullable<int> column { get; set; }
        public string groupName { get; set; }
        public Nullable<int> order { get; set; }
        public string dopAttr { get; set; }
        public Nullable<int> inherited { get; set; }
        public string fieldName { get; set; }
        public Nullable<int> showInInterface { get; set; }
        public Nullable<int> showInGrid { get; set; }
    }
}
