//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_userData
    {
        public int id { get; set; }
        public Nullable<int> table_id { get; set; }
        public Nullable<int> row_id { get; set; }
        public string props1 { get; set; }
        public string props2 { get; set; }
        public string props3 { get; set; }
        public string props4 { get; set; }
        public string props5 { get; set; }
        public Nullable<decimal> propn1 { get; set; }
        public Nullable<decimal> propn2 { get; set; }
        public Nullable<decimal> propn3 { get; set; }
        public Nullable<decimal> propn4 { get; set; }
        public Nullable<decimal> propn5 { get; set; }
        public Nullable<System.DateTime> propd1 { get; set; }
        public Nullable<System.DateTime> propd2 { get; set; }
        public Nullable<System.DateTime> propd3 { get; set; }
        public Nullable<System.DateTime> propd4 { get; set; }
        public Nullable<System.DateTime> propd5 { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public Nullable<int> createdByUser_id { get; set; }
        public string aspNetUser_Id { get; set; }
        public Nullable<int> prop1 { get; set; }
        public Nullable<int> prop2 { get; set; }
        public Nullable<int> prop3 { get; set; }
        public Nullable<int> prop4 { get; set; }
        public Nullable<int> prop5 { get; set; }
    }
}
