//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_doctor
    {
        public c_doctor()
        {
            this.sendEmail = 0;
        }
    
        public byte[] v { get; set; }
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public Nullable<short> sendEmail { get; set; }
        public Nullable<int> prop1 { get; set; }
        public Nullable<int> prop2 { get; set; }
        public Nullable<int> prop3 { get; set; }
        public Nullable<int> prop4 { get; set; }
        public Nullable<int> prop5 { get; set; }
        public Nullable<int> prop6 { get; set; }
        public Nullable<int> prop7 { get; set; }
        public Nullable<int> prop8 { get; set; }
        public Nullable<int> prop9 { get; set; }
        public Nullable<int> prop10 { get; set; }
    }
}
