//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mb_data
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<int> taxonomy_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<float> proportion { get; set; }
    }
}
