//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mb_reportField
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public string sectionCode { get; set; }
        public string fieldCode { get; set; }
        public string name { get; set; }
        public Nullable<int> lineNum { get; set; }
        public string ruleCode { get; set; }
        public Nullable<int> taxon_id { get; set; }
        public Nullable<double> refLowValue { get; set; }
        public Nullable<double> refHighValue { get; set; }
    }
}
