//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mb_taxonomy
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public string k { get; set; }
        public string p { get; set; }
        public string c { get; set; }
        public string o { get; set; }
        public string f { get; set; }
        public string g { get; set; }
        public string s { get; set; }
    }
}
