//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_reagent
    {
        public string barcode { get; set; }
        public int id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public decimal quantity { get; set; }
        public Nullable<int> prop1 { get; set; }
        public Nullable<int> prop2 { get; set; }
        public Nullable<int> prop3 { get; set; }
        public Nullable<int> prop4 { get; set; }
        public Nullable<int> prop5 { get; set; }
        public Nullable<int> prop6 { get; set; }
        public Nullable<int> prop7 { get; set; }
        public Nullable<int> prop8 { get; set; }
        public Nullable<int> prop9 { get; set; }
        public Nullable<int> prop10 { get; set; }
        public int reagentType_id { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> parent_id { get; set; }
    }
}
