//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_clones
    {
        public int id { get; set; }
        public string sampleBarcode { get; set; }
        public int patientId { get; set; }
        public string v { get; set; }
        public string j { get; set; }
        public string cdr3 { get; set; }
        public int Count { get; set; }
        public float fraction { get; set; }
        public Nullable<int> flags { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public string type { get; set; }
    }
}
