//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_custodyLog
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> logDateTime { get; set; }
        public Nullable<int> sample_id { get; set; }
        public Nullable<Sasha.Lims.DataAccess.Entities.Constants.SampleStatus> status_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public string aspNetUser_Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string singature { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> operation_id { get; set; }
    
        public virtual s_sample s_sample { get; set; }
    }
}
