//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class srv_request
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateTimeRequested { get; set; }
        public Nullable<int> data_id { get; set; }
        public Nullable<int> prop_id { get; set; }
    }
}
