//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class testUI
    {
        public int id { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string path { get; set; }
        public string parameters { get; set; }
        public string discription { get; set; }
        public string category { get; set; }
        public Nullable<int> exist { get; set; }
        public Nullable<int> enable { get; set; }
    }
}
