//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBillOfMaterial
    {
        public int Id { get; set; }
        public Nullable<int> RunId { get; set; }
        public string ReagentName { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> ReagentTypeId { get; set; }
        public int LifeCycleState { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public decimal InitialQuantity { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UnitName { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<int> OperationId { get; set; }
        public string OperationName { get; set; }
        public string Singature { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CommentsCount { get; set; }
        public Nullable<int> FilesCount { get; set; }
        public Nullable<int> ReagentId { get; set; }
        public Nullable<int> LogId { get; set; }
    }
}
