//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBioinformaticsRunList
    {
        public string cmd { get; set; }
        public string sqlCompleted { get; set; }
        public string sqlFail { get; set; }
        public int task_id { get; set; }
    }
}
