//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClientDoctorPatient
    {
        public int client_id { get; set; }
        public string client_name { get; set; }
        public int doctor_id { get; set; }
        public string doctor_title { get; set; }
        public string doctor_firstName { get; set; }
        public string doctor_lastName { get; set; }
        public int patient_id { get; set; }
        public string patient_firstName { get; set; }
        public string patient_lastName { get; set; }
    }
}
