//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDelIndexOptimize
    {
        public string DBName { get; set; }
        public string SchemaName { get; set; }
        public string ObjectName { get; set; }
        public string ObjectType { get; set; }
        public string ObjectTypeDesc { get; set; }
        public string IndexName { get; set; }
        public byte IndexType { get; set; }
        public string IndexTypeDesc { get; set; }
        public Nullable<bool> IndexIsUnique { get; set; }
        public Nullable<bool> IndexIsPK { get; set; }
        public Nullable<bool> IndexIsUniqueConstraint { get; set; }
        public Nullable<long> index_advantage { get; set; }
        public short Database_ID { get; set; }
        public int Object_ID { get; set; }
        public int Index_ID { get; set; }
        public long USER_SEEKS { get; set; }
        public long USER_SCANS { get; set; }
        public long USER_LOOKUPS { get; set; }
        public long USER_UPDATES { get; set; }
        public long SYSTEM_SEEKS { get; set; }
        public long SYSTEM_SCANS { get; set; }
        public long SYSTEM_LOOKUPS { get; set; }
        public long SYSTEM_UPDATES { get; set; }
        public Nullable<System.DateTime> Last_User_Seek { get; set; }
        public Nullable<System.DateTime> Last_User_Scan { get; set; }
        public Nullable<System.DateTime> Last_User_Lookup { get; set; }
        public Nullable<System.DateTime> Last_System_Seek { get; set; }
        public Nullable<System.DateTime> Last_System_Scan { get; set; }
        public Nullable<System.DateTime> Last_System_Lookup { get; set; }
        public string Filter_Definition { get; set; }
        public string Columns { get; set; }
        public string IncludeColumns { get; set; }
    }
}
