//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProperty
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }
        public Nullable<int> Number { get; set; }
        public string Type { get; set; }
        public Nullable<int> CommentsCount { get; set; }
        public Nullable<int> FilesCount { get; set; }
        public string Description { get; set; }
    }
}
