//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReagentLog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string VendorName { get; set; }
        public int ReagentId { get; set; }
        public int IsExists { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public decimal Quantity { get; set; }
        public string UnitName { get; set; }
        public string Location { get; set; }
        public System.DateTime OperationDate { get; set; }
        public int OperationId { get; set; }
        public string OperationName { get; set; }
        public string Singature { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
