//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSamplesBook
    {
        public int Id { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Well { get; set; }
        public string Doctor { get; set; }
        public string Patient { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<int> TubeTypeId { get; set; }
        public Nullable<int> CommentsCount { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<System.DateTime> CollectedDateTime { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<bool> IsChild { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> SampleWorkflowStatusId { get; set; }
        public Nullable<int> SampleStatusId { get; set; }
        public string ParentName { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> Prop1 { get; set; }
        public Nullable<int> Prop2 { get; set; }
        public Nullable<int> Prop3 { get; set; }
        public Nullable<int> Prop4 { get; set; }
        public Nullable<int> Prop5 { get; set; }
        public Nullable<int> Prop6 { get; set; }
        public Nullable<int> Prop7 { get; set; }
        public Nullable<int> Prop8 { get; set; }
        public Nullable<int> Prop9 { get; set; }
        public Nullable<int> Prop10 { get; set; }
        public string UserName { get; set; }
        public Nullable<int> SampleTypeId { get; set; }
        public Nullable<int> VolumeUnitId { get; set; }
        public string HospitalName { get; set; }
        public byte[] RowVersion { get; set; }
        public string BatchName { get; set; }
        public string Model { get; set; }
        public string Result { get; set; }
        public Nullable<int> ContentListCount { get; set; }
        public Nullable<int> FilesCount { get; set; }
        public string Files { get; set; }
        public Nullable<short> Sended_Id { get; set; }
        public string Sended { get; set; }
        public Nullable<int> Clones { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> HospitalId { get; set; }
        public string PropS1 { get; set; }
        public string PropS2 { get; set; }
        public string PropS3 { get; set; }
        public string PropS4 { get; set; }
        public string PropS5 { get; set; }
        public Nullable<decimal> PropN1 { get; set; }
        public Nullable<decimal> PropN2 { get; set; }
        public Nullable<decimal> PropN3 { get; set; }
        public Nullable<decimal> PropN4 { get; set; }
        public Nullable<decimal> PropN5 { get; set; }
        public Nullable<System.DateTime> PropD1 { get; set; }
        public Nullable<System.DateTime> PropD2 { get; set; }
        public Nullable<System.DateTime> PropD3 { get; set; }
        public Nullable<System.DateTime> PropD4 { get; set; }
        public Nullable<System.DateTime> PropD5 { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string SampleType { get; set; }
    }
}
