//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWorkflowRunList
    {
        public int Id { get; set; }
        public Nullable<int> TypeZId { get; set; }
        public string WfType { get; set; }
        public string Code { get; set; }
        public Nullable<int> CurProcessId { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedUserName { get; set; }
        public string UpdatedUserName { get; set; }
        public string CompletedUserName { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> CommentsCount { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Status { get; set; }
        public Nullable<int> FilesCount { get; set; }
        public string Files { get; set; }
    }
}
