//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_bom
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> run_id { get; set; }
        public Nullable<int> reagentType_id { get; set; }
        public Nullable<int> reagentLog_id { get; set; }
        public Nullable<int> currentReagent_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
    }
}
