//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasha.Lims.DataAccess.Entities.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_process
    {
        public byte[] v { get; set; }
        public int id { get; set; }
        public Nullable<int> run_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> dateStarted { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
        public Nullable<int> startedBy_id { get; set; }
        public Nullable<int> completedBy_id { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> createdBy_id { get; set; }
        public Nullable<int> updatedBy_id { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string result_path { get; set; }
        public Nullable<int> flags { get; set; }
    
        public virtual a_prop a_prop { get; set; }
        public virtual wf_run wf_run { get; set; }
    }
}
